-- ZAPOREDJE ATRIBUTOV MORE BITI ENAKO KOT JE V BAZI RAZPOREJENO -- 
-- VRSTNI RED (ČE SE SPRMENI) SI POGLEJ KO V BAZI KLIČEŠ SELECT* FROM entitetaXXX; --


INSERT INTO DOGODEK (KONEC_ODJAV ,KONEC_PRIJAV ,LOKACIJA ,MAX_OSEB ,MIN_OSEB ,NAZIV ,OPIS ,POTREBNO_POVABILO ,STATUS ,TRAJANJE ,ZACETEK ) values ('2018-09-15', '2018-09-14', 'Maribor', '7', '2', 'Dogodek v Mariboru', 'Pridite prosim', '0', 'prisoten', '2018-09-16', '2018-09-10');
INSERT INTO ORGANIZATOR(email,ime,priimek)VALUES('a ','a','a');
INSERT INTO PRIJAVA  (OCENA ,EMAIL ,IME ,PRIIMEK ,PRIJAVA ,STATUS ) values ('5', 'tonizunec', 'toni', 'žunec', 'ok', 'ok');

