CREATE TABLE ORGANIZATOR(
ID_organizator INTEGER NOT NULL, 
ime VARCHAR(20),
priimek VARCHAR(25),
email VARCHAR(75)

);
ALTER TABLE ORGANIZATOR ADD(CONSTRAINT PK_ORGANIZATOR PRIMARY KEY (ID_organizator));

CREATE TABLE DOGODEK(
ID_dogodek INTEGER NOT NULL,
naziv VARCHAR(100),
opis VARCHAR(3500),
lokacija VARCHAR(100),
zacetek DATE
trajanje TIME
konecPrijav DATE
konecOdjav DATE
minOseb INTEGER
maxOseb INTEGER
status VARCHAR(25),
potrebnoPovabilo BOOLEAN

);
ALTER TABLE DOGODEK ADD(CONSTRAINT PK_DOGODEK PRIMARY KEY (ID_dogodek));
ALTER TABLE DOGODEK ADD(CONSTRAINT TK_DOGODEK_ID_organizator FOREIGN KEY (TK_ID_organizator) REFERENCES (ID_organizator));



CREATE TABLE PRIJAVA(
ID_prijava INTEGER NOT NULL,
ime VARCHAR(20),
priimek VARCHAR(25),
datumPrijave DATE,
email VARCHAR(75),
ocena INTEGER,
komentar VARCHAR(500)

);
ALTER TABLE DOGPRIJAVAODEK ADD(CONSTRAINT PK_PRIJAVA PRIMARY KEY (ID_prijava));
ALTER TABLE PRIJAVA ADD(CONSTRAINT TK_PRIJAVA_ID_organizator FOREIGN KEY (TK_ID_organizator) REFERENCES (ID_organizator));
ALTER TABLE PRIJAVA ADD(CONSTRAINT TK_PRIJAVA_ID_dogodek FOREIGN KEY (TK_ID_dogodek) REFERENCES (ID_dogodek));





/*
CREATE TABLE POVABILO(
ID_povabilo INTEGER NOT NULL,
naziv varchar(50)
);
ALTER TABLE POVABILO ADD(CONSTRAINT PK_POVABILO PRIMARY KEY (ID_povabilo));
*/

